### ISSUE TITLE
报错求助：运行node getLavaRpc.js报错

### ISSUE THREAD

**Issue by blackshor** [0xsongsu/dailytask#14]
node getLavaRpc.js
璇疯緭鍏ヤ綘鐨勫瘑鐮? ***********
F:\gogogo\项目地\Lava脚本\dailytask\src\lavaNet\getLavaRpc.js:46
    let parts = text.split(':');
                     ^

TypeError: Cannot read properties of undefined (reading 'split')
    at decrypt (F:\gogogo\项目地\Lava脚本\dailytask\src\lavaNet\getLavaRpc.js:46:22)
    at CsvParser.<anonymous> (F:\gogogo\项目地\Lava脚本\dailytask\src\lavaNet\getLavaRpc.js:196:37)
    at CsvParser.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at CsvParser.writeRow (F:\gogogo\项目地\Lava脚本\dailytask\node_modules\csv-parser\index.js:192:10)
    at CsvParser.parseLine (F:\gogogo\项目地\Lava脚本\dailytask\node_modules\csv-parser\index.js:166:23)
    at CsvParser._transform (F:\gogogo\项目地\Lava脚本\dailytask\node_modules\csv-parser\index.js:252:16)
    at Transform._write (node:internal/streams/transform:175:8)

Node.js v18.16.0

![1710060349837](https://github.com/0xsongsu/dailytask/assets/58545771/789d0699-cae8-4f88-ac17-ccdbc3b48539)

**Comment by 666-eth** [comment]
![image](https://github.com/0xsongsu/dailytask/assets/77118877/b5c90947-add5-4afb-aae8-89f5eef1ce23)
这是啥问题呢

**Comment by 0xsongsu** [comment]
更新一下代码，修复了
